### ISSUE TITLE
Falha na comunicação entre MercadoPago e painel.

### ISSUE THREAD

**Issue by davidsecommerce** [esjdev/boostpanel#10]
Opa irmão, tranquilo? Eu adiciono os fundos, cai no checkout do mercadopago e pago normalmente, porém o painel não atualiza o saldo e transação no painel fica como pendente. Como consigo arrumar isso?

**Comment by esjdev** [comment]
Teria que analisar o código. Estou sem tempo para trabalhar no BoostPanel, por isso esta em OpenSource. Porém no momento, nenhum programador contribuiu. 

Pretendo atualizar o BoostPanel para o PHP 7.2, reformular ele todo. Porém não no momento, quando eu iniciar isso, vou avisar aqui nesse repositório para todos.
