### ISSUE TITLE
THANKS FOR CHANGING BOTH ISSUE

### ISSUE THREAD

**Issue by vraj1512** [esjdev/boostpanel#4]
I have just one query that what cron command we have to add in cron job list and also i want you to add **maintenance page** feature in future update and if you add this feature now then I **will be so happy** and **thank you** for this and also you know me i had mailed you regarding the panel,

**Comment by esjdev** [comment]
If I understand correctly what you would like. You access the documentation that comes in the Documentation folder. Access the documentation by your domain.
