### ISSUE TITLE
Users get logged out after making a successful payment.

### ISSUE THREAD

**Issue by imasifakhtar** [esjdev/boostpanel#9]
Whenever users try to add funds on the panel their money get deducted and they are redirected to the login page but the fund doesn't load in their accounts.

**Comment by davidsecommerce** [comment]
Hey bro, managed to fix this?

**Comment by imasifakhtar** [comment]
> Hey bro, managed to fix this?

No, unable to fix

**Comment by esjdev** [comment]
I would have to analyze the code. I'm out of time to work on BoostPanel, so it's on OpenSource. However, at the moment, no programmer contributed.

I intend to update BoostPanel to PHP >= 7.2, reformulate it all. But not at the moment, when I start this, I will notify here in this repository for everyone.

**Comment by jhonyee** [comment]
which paymet gateway not work??

**Comment by imasifakhtar** [comment]
> which paymet gateway not work??

For me it's the paytm and payunow.
